package org.nicehiro.ShopCar;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SHOPCAR".
 */
public class shopcar {

    /** Not-null value. */
    private byte[] id;
    private byte[] profile;
    private Float price;
    private byte[] imagelink;
    private Integer remain;
    private java.util.Date time;

    public shopcar() {
    }

    public shopcar(byte[] id) {
        this.id = id;
    }

    public shopcar(byte[] id, byte[] profile, Float price, byte[] imagelink, Integer remain, java.util.Date time) {
        this.id = id;
        this.profile = profile;
        this.price = price;
        this.imagelink = imagelink;
        this.remain = remain;
        this.time = time;
    }

    /** Not-null value. */
    public byte[] getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(byte[] id) {
        this.id = id;
    }

    public byte[] getProfile() {
        return profile;
    }

    public void setProfile(byte[] profile) {
        this.profile = profile;
    }

    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }

    public byte[] getImagelink() {
        return imagelink;
    }

    public void setImagelink(byte[] imagelink) {
        this.imagelink = imagelink;
    }

    public Integer getRemain() {
        return remain;
    }

    public void setRemain(Integer remain) {
        this.remain = remain;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    @Override
    public String toString() {
        return getId() + ":" + getTime() + "\n";
    }
}
